version: "3.9"

services:
  frontend:
    build:
      context: ./angular-app
      dockerfile: Dockerfile
    ports:
      - "80:4200"  
    container_name: angular-frontend
    depends_on:
      - backend
    env_file:
      - .env 
    profiles:
      - frontend

  backend:
    build:
      context: ./node-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: node-backend
    profiles:
      - backend


